# -*- coding: utf-8 -*-
"""Despliegue_MD_PF_PipeLine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQUASSjw8hUJKye6IFlfF97I43-FAhHH

# Pipes - Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Aplicar tubería
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Paso 1: Limpiar atípicos
def limpiar_atipicos(X):
    """Limpia valores atípicos reemplazándolos con np.nan"""
    # Limpiar LotFrontage (valores >= 270)
    X.loc[X["LotFrontage"] >= 270, "LotFrontage"] = np.nan

    # Limpiar TotalBsmtSF (valores > 5500)
    X.loc[X["TotalBsmtSF"] > 5500, "TotalBsmtSF"] = np.nan

    # Limpiar BsmtFinSF1 (valores > 5500)
    X.loc[X["BsmtFinSF1"] > 5500, "BsmtFinSF1"] = np.nan

    return X

#Cargamos el pipeline con el modelo
import pickle
filename = '/content/pipeline_modelo_final.pkl'
pipeline = pickle.load(open(filename, 'rb'))
pipeline

#Cargamos los datos futuros
data = pd.read_csv("/content/housing_sample.csv")
data.head()

#Añadir las columnas de categoría de año (necesarias para el pipeline)
if 'YearBuilt_Category' not in data.columns:
    data['YearBuilt_Category'] = pd.cut(
        data['YearBuilt'],
        bins=[1872, 1920, 1950, 1980, 2010],
        labels=["1872-1920", "1921-1950", "1951-1980", "1981-2010"],
        right=True,
        include_lowest=True
    )

if 'YearRemodAdd_Category' not in data.columns:
    data['YearRemodAdd_Category'] = pd.cut(
        data['YearRemodAdd'],
        bins=[1950, 1980, 2010],
        labels=["1950-1980", "1981-2010"],
        right=True,
        include_lowest=True
    )

!pip install streamlit
import streamlit as st

st.title("Predicción de precios de casas usando mi pipeline")

# Visualiza los datos que cargaste
st.write("Datos cargados:")
st.dataframe(data)

# Haz la predicción cuando el usuario presione un botón
if st.button('Predecir precio de las casas'):
    predicciones = pipeline.predict(data)
    st.write("Predicciones para las casas ingresadas:")
    for i, precio in enumerate(predicciones):
        st.success(f"Casa {i+1}: ${precio:,.2f}")

#Hacemos la predicción con el Tree
Y_rf = pipeline.predict(data)
print(Y_rf)

data['Prediccion']=Y_rf
data